### ISSUE TITLE
ImportError: cannot import name 'SessionMultipleFormWizardView'

### ISSUE THREAD

**Issue by 029xue** [vikingco/django-formtools-addons#3]
```
>>> from formtools_addons import SessionMultipleFormWizardView
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'SessionMultipleFormWizardView'
```

Any I missing something? Thanks.

**Comment by joncasdam** [comment]
is it still happening, @029xue ?

**Comment by joncasdam** [comment]
It doesn't seem to be an ongoing issue.

>  \>\>\> from formtools_addons import SessionMultipleFormWizardView
>  \>\>\> session = SessionMultipleFormWizardView()
>  \>\>\> session
>  \>\>\> \<SessionMultipleFormWizardView: forms: None\>
